#!/bin/bash

EXEC_PATH="../philosophers/philo"								#<------ YOUR PATH
T_LIMIT=10 													#<------ YOUR TIMEOUT IN SECONDS
T_DELAY_TOLERANCE=0											#<------ YOUR DELAY TOLERANCE IN MILLISECONDS, ZERO BY DEFAULT						
MEMCHECK_FLAGS="--leak-check=full --show-leak-kinds=all" 	#<------ YOUR FLAGS
HELGRIND_FLAGS="--tool=helgrind --trace-children=yes --fair-sched=yes" 							#<------ YOUR FLAGS
TSANITAZER="-fsanitize=thread"								#<------ YOUR FLAGS
TSAN_OPT="verbosity=4"										#<------ YOUR FLAGS
